### ISSUE TITLE
does not configure

### ISSUE THREAD

**Issue by sancelot** [m-pilia/sticky-notes#1]
CMake Error at CMakeLists.txt:6 (find_package):
  Could not find a package configuration file provided by "ECM" (requested
  version 0.0.11) with any of the following names:

    ECMConfig.cmake
    ecm-config.cmake

  Add the installation prefix of "ECM" to CMAKE_PREFIX_PATH or set "ECM_DIR"
  to a directory containing one of the above files.  If "ECM" provides a
  separate development package or SDK, be sure it has been installed.

**Comment by m-pilia** [comment]
Hello!
As the message says, it seems that [ECM](https://github.com/KDE/extra-cmake-modules) is not installed on your system, or CMake is not configured to find it. As the message says, you should make sure you have ECM installed (installation details depend upon your distribution, so I cannot help with it, you should check the relative documentation for your system).

If ECM is already installed but it is not visible to CMake, you should make sure that the directory containing `ECMConfig.cmake` is added to the CMake path: as the error message says, you can add it to [`CMAKE_PREFIX_PATH`](https://cmake.org/cmake/help/latest/variable/CMAKE_PREFIX_PATH.html) with something like
```
export CMAKE_PREFIX_PATH=$CMAKE_PREFIX_PATH;/usr/share/ECM/cmake
```
(`usr/share/ECM/cmake` in this example, but use the right path for your installation) or in alternative set `ECM_DIR` accordingly
```
export ECM_DIR=usr/share/ECM/cmake
```
